openapi: 3.0.0
info:
  title: Sales provider
  version: '1.0'
  description: API provided by Sales system for consumed by ERP
  license:
    name: MIT
  contact:
    email: joke@nakhon.net
servers:
  - url: 'http://localhost:3000'
paths:
  '/deliveries/{id}':
    get:
      summary: Get delivery info
      tags:
        - transaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  delivery:
                    $ref: '#/components/schemas/delivery'
      operationId: get-deliveries
      description: Get delivery info
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
  '/purchasings/{id}/deliveries':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: "List purchasing's deliveries"
      tags:
        - transaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
      operationId: get-purchasings-id-deliveries
      description: "List purchasing's deliveries"
    post:
      summary: Create delivery
      operationId: post-purchasing-id-deliveries
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
      description: Create delivery
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                deliveryDate:
                  type: string
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productCode:
                        type: string
                      quantity:
                        type: integer
                      unitCode:
                        type: string
      tags:
        - transaction
  '/deliveries/{id}/statuses':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    post:
      summary: Add delivery status
      operationId: post-deliveries-id-statuses
      responses:
        '201':
          description: Created
      description: Add delivery status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                statusDate:
                  type: string
                  format: date-time
                statusCode:
                  type: string
                statusDetail:
                  type: string
      tags:
        - transaction
components:
  schemas:
    delivery:
      title: delivery
      type: object
      description: Delivery info
      properties:
        id:
          type: integer
        code:
          type: string
        purchasing:
          $ref: './sales-comsumer.v1.yaml#/components/schemas/purchasing'
        deliveryStatus:
          type: array
          items:
            $ref: '#/components/schemas/deliveryStatus'
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: './sales-comsumer.v1.yaml#/components/schemas/product'
              quantity:
                type: integer
              productUnit:
                $ref: './sales-comsumer.v1.yaml#/components/schemas/productUnit'
    deliveryStatus:
      title: deliveryStatus
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        statusDate:
          type: string
          format: date-time
        statusCode:
          type: string
        statusDetail:
          type: string
      description: Delivery status info
tags:
  - name: member
  - name: product
  - name: transaction
